---
- hosts: all

  tasks:
    - apt: update_cache=yes cache_valid_time=1800
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - ack-grep
        - exuberant-ctags
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - easy_install: name=pip
      sudo: yes
      tags: always

    - pip: name={{ item }} state=latest
      sudo: yes
      with_items:
        - pylint
        - ansible-lint
        - numpy
        - pandas
      tags: always
