---
- hosts: all

  tasks:
    - apt_repository: repo='ppa:staticfloat/juliareleases' state=present
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - apt_repository: repo='ppa:staticfloat/julia-deps' state=present
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - apt: update_cache=yes cache_valid_time=1800
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - ack-grep
        - exuberant-ctags
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - julia
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - easy_install: name=pip
      become: yes
      tags: always

    - pip: name={{ item }} state=latest
      become: yes
      with_items:
        - pylint
        - ansible-lint
      tags: always
