---
- hosts: all
  tasks:
    - file: src=dotfiles/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim

    - file: path=~/.vim/spell state=directory

    - shell: vim -i NONE -c VundleUpdate -c quitall
